### ISSUE TITLE
KeyError 'taskID' when 'AgentResults' None

### ISSUE THREAD

**Issue by daniel-ammann** [byt3bl33d3r/DeathStar#35] opened 2017-10-28 17:22 UTC
Sorry, if I'm doing something wrong. I already tried your Empire fork, as suggested in a similar issue..

> [DEBUG] Agent: NFXL2CHU => Executed Module => success: True taskID: 1 msg: 'tasked agent NFXL2CHU to run module powershell/management/get_domain_sid'
[DEBUG] Agent: NFXL2CHU => Result Buffer: {'AgentName': 'NFXL2CHU', 'AgentResults': [None]}
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "./DeathStar.py", line 59, in __run
    self.__run_backup()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./DeathStar.py", line 585, in pwn_the_shit_out_of_everything
    recon(agent_name)
  File "./DeathStar.py", line 507, in recon
    domain_sid = get_domain_sid(agent_name)
  File "./DeathStar.py", line 213, in get_domain_sid
    results = execute_module_with_results('powershell/management/get_domain_sid', agent_name)
  File "./DeathStar.py", line 180, in execute_module_with_results
    if result['taskID'] == r['taskID']:
KeyError: 'taskID'

**Comment by crossmxn** [comment] 2017-11-09 06:51
Im getting the same error.. Im running empire on the latest commit and so do DeathStar

**Comment by whoot** [comment] 2017-11-10 09:34
Same here

**Comment by chryzsh** [comment] 2017-11-10 16:37
Same here

**Comment by utkusen** [comment] 2017-11-15 20:58
I worked on that problem a bit and it seems to be Empire's problem. I opened an issue: https://github.com/EmpireProject/Empire/issues/822

If they fix it, Deathstar will also be fixable

**Comment by LIZySARA** [comment] 2017-11-18 15:31
File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "./DeathStar.py", line 59, in __run
    self.__run_backup()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "./DeathStar.py", line 589, in pwn_the_shit_out_of_everything
    for user in get_loggedon(agent_name):
  File "./DeathStar.py", line 393, in get_loggedon
    results = execute_module_with_results('powershell/situational_awareness/network/powerview/get_loggedon', agent_name, module_options)
  File "./DeathStar.py", line 180, in execute_module_with_results
    if result['taskID'] == r['taskID']:
KeyError: 'taskID'

**Comment by byt3bl33d3r** [comment] 2017-12-08 12:31
Duplicate of #29. Please track the issue there.
Thanks

**Closed by byt3bl33d3r** 2017-12-08 12:31 UTC
