### ISSUE TITLE
Connection Error. Check Empire RESTful API

### ISSUE THREAD

**Issue by cgsupport** [byt3bl33d3r/DeathStar#28] opened 2017-09-18 15:09 UTC
Sorry if this is obvious, but I'm having trouble figuring it out, and can't see anyone that has had this issue (since not having to fork your copy of Empire).

I have a fresh install of Kali (updated). Installed Empire and DeathStar (installed python3 too).

`./empire --rest --debug --username empireadmin --password Password123`

`curl --insecure -i -H "Content-Type: application/json" https://localhost:1337/api/admin/login -X POST -d '{"username":"empireadmin", "password":"Password123"}'`

> HTTP/1.0 200 OK
> Content-Type: application/json
> Content-Length: 58
> Server: Werkzeug/0.12.2-dev Python/2.7.13
> Date: Mon, 18 Sep 2017 15:03:00 GMT
> 
> {
>   "token": "u6gw3hgu8lrf71xs40re0sm7vhoovo3g5b4v0aps"
> }

The above appears to work. But when trying DeathStar (with and without python3):

`./DeathStar.py --url "https://localhost:1337" -u "empireadmin" -p "Password123"`

> [*] Powering up the Death Star
> [-] Connection Error. Check Empire RESTful API

I never get any connection attempts in the empire terminal. So I'm not even sure its trying to make a connection; any idea what I'm missing?

**Comment by byt3bl33d3r** [comment] 2017-09-21 11:00
I'll spin up a kali instance and check this out now. Hang tight

**Comment by byt3bl33d3r** [comment] 2017-09-21 12:03
There seems to be an issue with the Python requests library on Kali not wanting to negotiate TLSv < 1.2.
I submitted a PR here https://github.com/EmpireProject/Empire/pull/712, should be merged soon hopefully. 

Thanks

**Comment by dinvisible1** [comment] 2017-10-01 19:11
any update on this? i think i have the same issue, by the way great work with Deathstar as well as you're other stuff im a follower of your blog!

**Comment by kofx2002** [comment] 2017-10-08 09:55
i have the same issue 
[*] Powering up the Death Star
[-] Connection Error. Check Empire RESTful API

**Comment by DanMcInerney** [comment] 2017-10-11 01:50
Solution:
cd Empire/
git reset --hard 2677363e508c81834b27c31ae534a5474d37eda5
pip3 install pyopenssl

**Comment by ohpe** [comment] 2017-10-11 12:14
@DanMcInerney your solution doesn't work for me.

**Comment by nem0n** [comment] 2017-10-18 01:39
Same problem in here too with Kali

**Comment by kofx2002** [comment] 2017-10-24 15:11
still the same problem

**Comment by OneDollarr** [comment] 2017-10-26 17:34
still the same problem

**Comment by n8tr0n** [comment] 2017-10-27 16:55
ok. I installed python 3.5.3 in a virtual environment using pipenv. Ran Deathstar in that context. The error didn't occur. listeners were being created in empire. So, I think the issue is with the python 3 version installed in Kali.

**Comment by n8tr0n** [comment] 2017-10-27 16:58
I was able to get this working in Debian "stretch" so I compared the python 3 versions and noticed the discrepancy.

**Comment by ohpe** [comment] 2017-10-28 15:55
That's true, there's something wrong in the python3 in Kali.
However, using the virtualenv trick it fixes the problem:
```bash
cd ~/Tools/DeathStar
virtualenv -p python3 deathstar_env
source deathstar_env/bin/activate
pip3 install -r requirements.txt
```

**Comment by OneDollarr** [comment] 2017-10-28 17:19
[-] I find your lack of faith disturbing... (Authentication Failed)

**Comment by ohpe** [comment] 2017-10-28 17:27
@OneDollarr that's because the empire password is different from `Password123`. Reset the db and set that password or use `-p "yourempirepwd"`

**Comment by byt3bl33d3r** [comment] 2017-12-08 12:29
Closing since this was merged.

**Closed** 2017-12-08 12:29 UTC
Labels: bug, third-party
