### ISSUE TITLE
Error while launching DeathStar with Empire REST API

### ISSUE THREAD

**Issue by str4n63r** [byt3bl33d3r/DeathStar#37] opened 2017-11-03 11:56 UTC
**Machine Info:**
OS: Kali Linux 2017.1 AMD-64
Empire Version: Latest pull from GitHub
DeathStar Version: Latest pull from GitHub

**Error Info:**
[*] Powering up the Death Star
[*] Created Death Star listener => {'success': 'listener DeathStar successfully started'}
[*] Polling for agents
[+] New Agent => Name: NL1SR3W9 IP: x.x.x.x HostName: Dummy_Machine UserName: Domain\Dummy_User HighIntegrity: 1
[*] Agent: NL1SR3W9 => Starting recon
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "./DeathStar.py", line 59, in __run
    self.__run_backup()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "./DeathStar.py", line 585, in pwn_the_shit_out_of_everything
    recon(agent_name)
  File "./DeathStar.py", line 507, in recon
    domain_sid = get_domain_sid(agent_name)
  File "./DeathStar.py", line 213, in get_domain_sid
    results = execute_module_with_results('powershell/management/get_domain_sid', agent_name)
  File "./DeathStar.py", line 180, in execute_module_with_results
    if result['taskID'] == r['taskID']:
KeyError: 'taskID'

**Scenario:**
Launched DeathStar with Empire and after getting an agent in Empire DeathStar showed above error

**Comment by byt3bl33d3r** [comment] 2017-12-08 12:30
Duplicate of #29

**Closed by byt3bl33d3r** 2017-12-08 12:30 UTC
