### ISSUE TITLE
Exception in thread

### ISSUE THREAD

**Issue by hawaii67** [byt3bl33d3r/DeathStar#24] opened 2017-08-11 09:53 UTC
I get the following error:

`[*] Powering up the Death Star
[*] Polling for agents
[+] New Agent => Name: M3D46YX5 IP: 10.1.1.1 HostName: XXXXXXX UserName: xxxxx\xxxxx HighIntegrity: 0
[*] Agent: M3D46YX5 => Starting recon
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "DeathStar.py", line 59, in __run
    self.__run_backup()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "DeathStar.py", line 533, in pwn_the_shit_out_of_everything
    recon(agent_name)
  File "DeathStar.py", line 470, in recon
    for member in get_group_member(agent_name):
  File "DeathStar.py", line 201, in get_group_member
    results = execute_module_with_results('powershell/situational_awareness/network/powerview/get_group_member', agent_name, module_options)
  File "DeathStar.py", line 170, in execute_module_with_results
    if result['taskID'] == r['taskID']:
KeyError: 'taskID'
`

**Comment by byt3bl33d3r** [comment] 2017-08-17 05:33
Duplicate of #12. Closing.

**Closed by byt3bl33d3r** 2017-08-17 05:33 UTC
Labels: duplicate
