### ISSUE TITLE
Fails on german domains

### ISSUE THREAD

**Issue by whoot** [byt3bl33d3r/DeathStar#23] opened 2017-08-03 16:27 UTC
Hey,

DeathStar does NOT work on german systems/domains, because the Group "Domain Admins" does not exist. In german it is called **"Domänen-Admins"**.
This will result in : 
**[+] Agent: .... => Found 0 members for the '"Domain Admins"' group: []**

I tried to fix it manually, however using UTF-8 encoding and changing every occurrence of "Domain Admins" in "Domänen-Admins" in the _DeathStar.py_ and _[Empire]/*_ did not fix the issue, but generated the error message:
**Agent: .... => Error executing module 'powershell/situational_awareness/network/powerview/get_group_member': Expecting value: line 1 column 1 (char 0)**

Maybe someone can help?

**Comment by byt3bl33d3r** [comment] 2017-08-17 05:34
Duplicate of #18. I'll resolve this as soon as i get some time.

**Closed by byt3bl33d3r** 2017-08-17 05:34 UTC
Labels: duplicate
