### ISSUE TITLE
TypeError: string indices must be integers & TypeError: 'NoneType' object is not subscriptable Errors

### ISSUE THREAD

**Issue by nem0n** [byt3bl33d3r/DeathStar#41] opened 2017-12-10 23:09 UTC
Hi again,

I was trying to run Death Star on Kali but during my attempts, I got these error 

![screenshot from 2017-12-10 18-02-36](https://user-images.githubusercontent.com/25449049/33810633-32e37050-ddd5-11e7-8c11-7c31baa31ba7.png)
![screenshot from 2017-12-10 18-06-10](https://user-images.githubusercontent.com/25449049/33810634-330b9742-ddd5-11e7-807e-94496c671889.png)

What am I wondering that is the issue about my Linux?

**Comment by zlgxzswjy** [comment] 2017-12-12 03:47
Me,too!

**Comment by byt3bl33d3r** [comment] 2017-12-18 17:24
This seems to be a duplicate of #29  which was fixed.

Comment below if it's not the case

**Closed by byt3bl33d3r** 2017-12-18 17:24 UTC
